[workspace]
members = [
  "apps/zifile-cli",
  "apps/zifile-desktop",
  "crates/zifile-core",
]
resolver = "3"

[workspace.package]
version = "0.1.0-alpha.1"
edition = "2024"
rust-version = "1.88"
authors = ["ZiCode <ax2@zicode.com>"]
license = "MIT"
repository = "https://github.com/ax2/zifile"
homepage = "https://ax2.github.io/zifile/"

[workspace.dependencies]
clap = { version = "4.6.6", features = ["derive"] }
criterion = { version = "0.8.2", features = ["html_reports"] }
iced = { version = "0.14.0", features = ["tokio"] }
rfd = "0.17.2"
sys-locale = "0.3.2"
thiserror = "2.0.20"
zip = "8.2.0"
sevenz-rust2 = "0.20.1"
tar = { version = "0.4.46", default-features = false }
flate2 = "1.1.9"
zstd = "0.13.3"
xz2 = { version = "0.1.7", features = ["static"] }
bzip2 = "0.6.1"
lz4_flex = "0.14.0"
brotli = "8.0.4"
walkdir = "2.5.0"
tempfile = "3.27.0"
winresource = "0.1.31"
zifile-core = { path = "crates/zifile-core", version = "0.1.0-alpha.1" }

[profile.release]
codegen-units = 1
lto = "thin"
strip = "symbols"
