[package]
name = "zifile-shell"
description = "Windows 11 File Explorer command extension for ZiFile"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_Globalization",
  "Win32_System_Com",
  "Win32_System_LibraryLoader",
  "Win32_System_Ole",
  "Win32_UI_Shell",
] }
windows-core.workspace = true
zifile-core.workspace = true

[dev-dependencies]
tempfile.workspace = true
