[package]
name = "zifile-desktop"
description = "Modern Windows desktop interface for ZiFile"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
build = "build.rs"

[dependencies]
iced.workspace = true
rfd.workspace = true
zifile-core.workspace = true

[build-dependencies]
winresource.workspace = true
